# Project configuration
project:
  name: "nayo-website"
  description: "Nancholi Youth Organisation Website"
  framework: "php"

# Deployment settings
deployment:
  environment: "production"
  build:
    command: "composer install && npm install && npm run build"
    output: "dist"
  server:
    type: "apache"
    port: 80

# Asset management
assets:
  images:
    directory: "images"
    optimization: true
    formats: ["png", "jpg", "jpeg", "svg"]
  css:
    directory: "css"
    minification: true
  js:
    directory: "js"
    minification: true

# Environment variables
environment:
  variables:
    - name: "APP_ENV"
      value: "production"
    - name: "DEBUG"
      value: "false"

# Cache configuration
cache:
  enabled: true
  directories:
    - "vendor"
    - "node_modules"
    - ".cache"

# Security settings
security:
  headers:
    - name: "X-Frame-Options"
      value: "DENY"
    - name: "X-Content-Type-Options"
      value: "nosniff"
    - name: "X-XSS-Protection"
      value: "1; mode=block"
  https: true
